Portfolio/Portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
    path('work-experience/', include("workExperience.urls")),
    path('projects/', include("projects.urls")),
    path('certifications/', include("certifications.urls")),
]

Portfolio/certifications/urls.py
from django.urls import path
from . import views
app_name = "certifications"
urlpatterns = [
    path('', views.certifications, name="certifications"),
]

Portfolio/home/urls.py
from django.urls import path
from . import views
app_name = "home"
urlpatterns = [
    path('', views.home, name="home"),
]

Portfolio/projects/urls.py
from django.urls import path
from . import views
app_name = "projects"
urlpatterns = [
    path('', views.projects, name="projects"),
]

Portfolio/workExperience/urls.py
from django.urls import path
from . import views
app_name = "workExperience"
urlpatterns = [
    path('', views.work_experience, name="workExperience"),
]

Portfolio/certifications/models.py
from django.db import models

# Create your models here.

Portfolio/certifications/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.


def certifications(request):
    template = loader.get_template("certifications/certifications.html")
    return HttpResponse(template.render({}, request))

Portfolio/home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.


def home(request):
    template = loader.get_template("home/home.html")
    return HttpResponse(template.render({}, request))

Portfolio/projects/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.


def projects(request):
    template = loader.get_template("projects/projects.html")
    return HttpResponse(template.render({}, request))

Portfolio/workExperience/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
# Create your views here.


def work_experience(request):
    template = loader.get_template("workExperience/workExperience.html")
    return HttpResponse(template.render({}, request))

Portfolio/certifications/templates/certifications/certifications.html
{% include 'navbar.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <div class="col-md-9" style="padding: 0!important;height: 100vh;overflow: auto;scroll-behavior: smooth;">
            <a href="#gotop" id="button"><i class="fa fa-chevron-up"></i></a>
            <div id="gotop" class="d-flex flex-column">
                <img style="max-width: 100%;max-height: 360px;overflow-y: hidden;filter: blur(2px);-webkit-filter: blur(2px);" src="https://images.unsplash.com/photo-1462536943532-57a629f6cc60?ixlib=rb-1.2.1&auto=format&fit=crop&w=752&q=80" alt="" class="img-responsive border border-light">
                <div class="modal-content-font display-4 text-white" style="position:absolute;top: 25%;left: 50%;transform: translate(-50%,-50%);">Certifications</div>
                <div class="row no-gutters">
                    <div class="col-md-6 text-center">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'javabasic.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Java Basic</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#javabasic">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'restapi.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">REST API</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#restapi">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'problemsolvingbasic.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Problem Solving Basic</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#problemsolvingbasic">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'pythonbasic.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Problem Solving Basic</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#pythonbasic">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6 text-center">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'dsmlexcellence.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Data Science and Machine Learning Excellence</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#dsmlexcellence">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'dsmlcomplete.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Data Science and Machine Learning Completion</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#dsmlcomplete">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'taship.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Online Teaching Assistant</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#tashipcertificate">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'udacitynano.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Udacity Full Stack Nano Degree</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#udacitynano">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6 text-center">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%;height: 360px;overflow-y: hidden;" src="{% static 'ccdsap.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Bachelor of Technology</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#ccdsap">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6 text-center">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%;height: 360px;overflow-y: hidden;" src="{% static 'btech.png' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Bachelor of Technology</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#btech">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'styles.css' %}">
    <div class="container-fluid">
      <div class="row no-gutters">
        <div class="col-md fixed panel" style="padding: 0!important;">
            <div class="sticky-top">
                <img src="https://images.unsplash.com/photo-1536148935331-408321065b18?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" style="height: 100vh; width: 100%" alt="My Image">
            </div>
        </div>
        <div class="col-md panel">
            <div class="text-center mt-5">
                <div style="font-family: 'PT Serif', serif" class="display-3 my-3 mx-3">Gourab Sinha</div>
                <div class="display-5 mx-5 text-secondary">First and foremost, I love writing code. Since my first program to print "Hello World" to produce the desired output for problems, I have been obsessed with the thought of solving practical problems using software. Software Engineering is one of the puzzles that has no end, where my interest comes. Each day solve one problem and the next day another problem comes, that makes me engage passionately. I believe programming has the capacity to transform and improve the lives of people around the globe.</div>
            </div>
            <div class="text-center panel">
                <div class="btn" style="font-family: 'PT Serif', serif">
                    <a href="{% url 'workExperience:workExperience' %}" class="btn btn-primary btn-rounded btn-md btn-block mt-5" style="height: 75%;">Work Experience</a>
                    <a href="{% url 'projects:projects' %}" class="btn btn-primary btn-rounded btn-md btn-block mt-5" style="height: 75%;">Projects</a>
                    <a href="{% url 'certifications:certifications' %}" class="btn btn-primary btn-rounded btn-md btn-block mt-5" style="height: 75%;">Certificates</a>
                    <a href="#" data-toggle="modal" data-target="#skills" class="btn btn-primary btn-rounded btn-md btn-block mt-5" style="height: 75%;">Skills</a>
                    <a href="#" data-toggle="modal" data-target="#achievements" class="btn btn-primary btn-rounded btn-md btn-block mt-5" style="height: 75%;">Achievements</a>
                    <a href="#" data-toggle="modal" data-target="#resume" class="btn btn-primary btn-rounded btn-md btn-block mt-5" style="height: 75%;">Resume</a>
                </div>
                <div class="d-md-block mt-4 mb-5">
                    <a href="https://twitter.com/gourab19964u" class="text-black mx-2">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/gourabsinha/" class="text-black mx-2">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="https://github.com/gourab-sinha" class="text-black mx-2">
                        <i class="fab fa-github"></i>
                    </a>
                    <a href="https://www.instagram.com/gourab__sinha" class="text-black mx-2">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="mailto:gourab19964u@gmail.com" class="text-black mx-2">
                        <i class="fas fa-envelope"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="modal" id="skills">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">
                            <h5>Skills</h5>
                        </div>
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="d-flex flex-column modal-content-font">
                            <img style="height: 50%;width: 100%;" src="https://images.unsplash.com/photo-1550439062-609e1531270e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="">
                            <ul>
                                <li>Programming : C++, Python, Numpy, Pandas, BeautifulSoup, SQL Server, Java(Basic), HTML,CSS</li>
                                <li>Web Frameworks : Django, Flask, Bootstrap</li>
                                <li>Version Control : Git</li>
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer modal-content-font">
                        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    <div class="modal" id="achievements">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">
                            <h5>Achievements</h5>
                        </div>
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="d-flex flex-column modal-content-font">
                            <img style="height: 50%;width: 100%;" src="https://images.unsplash.com/photo-1578269174936-2709b6aeb913?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80" alt="">
                            <ul>
                                <li>1st Runner up TIE Hackathon Chandigarh, 2017</li>
                                <li>Codeapoclaypse 3.0 Final Round, 2018</li>
                                <li>Codechef SnackDown 2019 Online Elimination Round</li>
                            </ul>
                        </div>
                    </div>
                    <div class="modal-footer modal-content-font">
                        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    <div class="modal" id="resume">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <div class="modal-title">
                            <h5>Resume</h5>
                        </div>
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div style="height: 100vh;width: 100%;" class="modal-body">
                        <div class="d-flex flex-column modal-content-font">
                            <iframe src="https://drive.google.com/file/d/11Y79rx38sVGp1ekKaUcaxmJKyPpA8ZlR/preview" style="width:100%; height:600px;"></iframe>
                        </div>
                    </div>
                    <div class="modal-footer modal-content-font">
                        <a href="https://drive.google.com/uc?export=download&id=11Y79rx38sVGp1ekKaUcaxmJKyPpA8ZlR" target="_blank" rel="noopener noreferrer" class="btn btn-primary">Download</a>
                        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

Portfolio/projects/templates/projects/projects.html
{% include 'navbar.html' %}
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        <div class="col-md-9" style="padding: 0!important;height: 100vh;overflow: auto;scroll-behavior: smooth;">
            <a class="btn btn-primary" href="#gotop" id="button"><i class="fa fa-chevron-up"></i></a>
            <div id="gotop" class="d-flex flex-column">
                <img style="max-width: 100%;filter: blur(2px);-webkit-filter: blur(2px);" src="{% static 'projects/ProjectHeader.jpg' %}" alt="" class="img-responsive border border-light">
                <div class="modal-content-font display-4 text-white" style="position:absolute;top: 20%;left: 50%;transform: translate(-50%,-50%);">Projects</div>
                <div class="row no-gutters">
                    <div class="col-md-6 text-center">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/portfolio.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Portfolio</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#portfolioProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/textclass.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Text Classification</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#textclassProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/instagram.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Instagram Bot</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#instabotProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/zomato.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Zomato Data Analyser</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#zomatoProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/casestudy.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Case Study for Startup Fundings</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#casestudyProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/linuxserver.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Linux Server Configuration</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#serverconfigProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row no-gutters">
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/restaurant.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Restaurant Items Catalog</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#restaurantProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card shadow" style="width:100%;">
                            <div class="hovereffect">
                                <img style="width: 100%" src="{% static 'projects/loganalysis.jpg' %}" alt="" class="img-responsive border border-light">
                                <div class="overlay">
                                    <div class="hover-body-content">
                                        <div class="d-flex flex-column">
                                            <div class="title">Log Analysis</div>
                                            <button style="color: white" class="btn btn-link" data-toggle="modal" data-target="#loganalyseProject">See More</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=PT+Serif&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

  <title>Gourab Sinha</title>
</head>

<body class="bg-light">
  <!-- START HERE -->
  {% block content %}
  {% endblock content %}


  <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script>
    // Get the current year for the copyright
    $('#year').text(new Date().getFullYear());

  </script>
</body>

</html>